[project]
name = "call-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "edge-tts>=7.2.8",
    "fastapi>=0.136.1",
    "faster-whisper>=1.2.1",
    "langchain",
    "langchain-ollama>=1.1.0",
    "numpy",
    "passlib[bcrypt]>=1.7.4",
    "pydantic[email]>=2.13.4",
    "pydantic-settings>=2.14.0",
    "pydub>=0.25.1",
    "python-dotenv>=1.2.2",
    "python-jose[cryptography]>=3.5.0",
    "sqlalchemy>=2.0.49",
    "uvicorn>=0.46.0",
    "webrtcvad-wheels>=2.0.14",
    "websockets>=16.0",
    "python-multipart>=0.0.27",
    "bcrypt<4.0.0",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.2.1",
]
